### ISSUE TITLE
Civilian Jobs

### ISSUE THREAD

**Issue by DuckingSmexy** [AaronWeber53/SRC-RP-Discussions#172]
After doing extensive testing on all the civilian jobs, none of them pay well, they're very inconsistent. Garbage is the only job that makes you actual money, but this morning it made me do a run from 9 am to 10 am and I only earned 17K. If you don't believe me, I have 3 other people who did shorter runs and made more money.

**Comment by AaronWeber53** [comment]
Civilian jobs are aimed to make on average 20k per hour. They are not meant to make 20k per hour on the dot but sometimes make more or less. Certain jobs as well will pay better when you upgrade them like trucking will make more money when you upgrade from city deliveries to semi truck driving. We will be adjusting payouts still as we go since we have not been able to fully test those out.
